#pragma once
#include <Windows.h>
#include <memory>
//#include <dxgi.h>
//#include <d3dcommon.h>
#include <d3d11.h>
//#include <DirectXMath.h>
#include <string>
#include <chrono>
#include <algorithm>
#include <iostream>
#include <unordered_map>
#include <queue>
#include <bitset>
#include <optional>
#include <d3d11.h>
#include <stdio.h>
#include <SDL.h>
#include <SDL_syswm.h>