#pragma once
#include <memory>
#include <string>
#include <sstream>
#include <chrono>
#include <algorithm>
#include <iostream>
#include <unordered_map>
#include <functional>
#include <queue>
#include <deque>
#include <bitset>
#include <optional>
#include <stdio.h>
#include <fstream>
#include <filesystem>
#include <glad/glad.h>
#include <glm.hpp>
#include <gtc/matrix_transform.hpp>
#include <gtc/type_ptr.hpp>

#include <GLFW/glfw3.h>